-- Extrae asignaturas del JSON de Arquitectura (DCAYT) e inserta en la tabla `items` como categoria 'asignatura'.
-- Ignora el atributo `Comisiones` y solo crea la materia con sus metadatos.

BEGIN;

WITH payload AS (
  SELECT $$
{
  "carrera": "Arquitectura",
  "codigo": "ARQ",
  "organizacion_curricular": "/index.php/carreras/ciencias-aplicadas-y-tecnologia/arquitectura/2-uncategorised/634-organizacion-curricular-arquitectura",
  "plan_de_estudios": "/files/ARQUITECTURA_UNM_2019_versin_difusin_20240404.pdf",
  "asignaturas": [
    {"Año":1,"Código":2311,"Asignatura-Actividad":"TALLER DE ARQUITECTURA I","Correlatividad Débil":null,"Correlatividad Fuerte":null,"Horas semanales teórico-prácticas":7,"Cuatrimestre":"1-2","Comisiones":[{"Comisión":"2311-01","Docente/s (1)":"ESTARELLAS Victoria / RANERO María Laura","Día/s y horario/s":"MAR 9 A 13 Y VIE 9 A 12","Turno":"Mañana","Aula/s":"7 DARACT II ","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2311-02","Docente/s (1)":"ACEVEDO Ayelén  / MASCARÓ Pablo","Día/s y horario/s":"MAR 9 A 13 Y VIE 9 A 12","Turno":"Mañana","Aula/s":"7 DARACT II","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2311-03","Docente/s (1)":"ESTARELLAS Victoria / BALAGUER María del Carmen","Día/s y horario/s":"MAR 18 A 22 Y VIE 18 A 21","Turno":"Noche","Aula/s":"7 DARACT II","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2311-04","Docente/s (1)":"GODOY Leonardo Alberto / ANDRADA Laura","Día/s y horario/s":"MAR 18 A 22 Y VIE 18 A 21","Turno":"Noche","Aula/s":"7 DARACT II","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2311-05","Docente/s (1)":"CANCELA Eugenia / AGUILAR Pablo","Día/s y horario/s":"MAR 13:30 A 17:30 Y VIE 14 A 16","Turno":"Tarde","Aula/s":"5 DORREGO","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"}]},
    {"Año":1,"Código":2312,"Asignatura-Actividad":"MATEMÁTICA I","Correlatividad Débil":null,"Correlatividad Fuerte":null,"Horas semanales teórico-prácticas":4,"Cuatrimestre":1,"Comisiones":[{"Comisión":"2312-01","Docente/s (1)":"GUERRERO, Virginia / LACABA María Cecilia","Día/s y horario/s":"JUE 9 A 13","Turno":"Mañana","Aula/s":"7 DARACT II","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2312-02","Docente/s (1)":"FERNANDEZ Ana Laura / PEREZ ORONA Marcelo","Día/s y horario/s":"JUE 9 A 13","Turno":"Mañana","Aula/s":"7 DARACT II","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2312-03","Docente/s (1)":"REYNOSO Laura / MARSAGLIA Walter","Día/s y horario/s":"JUE 18 A 22","Turno":"Noche","Aula/s":"7 DARACT II","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2312-04","Docente/s (1)":"GUERRERO Virginia / PEREZ ORONA Marcelo","Día/s y horario/s":"JUE 18 A 22","Turno":"Noche","Aula/s":"7 DARACT II","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"}]},
    {"Año":1,"Código":2312,"Asignatura-Actividad":"MATEMÁTICA I","Correlatividad Débil":null,"Correlatividad Fuerte":null,"Horas semanales teórico-prácticas":4,"Cuatrimestre":2,"Comisiones":[{"Comisión":"2312-05","Docente/s (1)":"GUERRERO Virginia / PEREZ ORONA Marcelo","Día/s y horario/s":"JUE 13:30 A 17:30","Turno":"Tarde","Aula/s":"***","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"}]},
    {"Año":1,"Código":2313,"Asignatura-Actividad":"DIBUJO ARQUITECTÓNICO I","Correlatividad Débil":null,"Correlatividad Fuerte":null,"Horas semanales teórico-prácticas":4,"Cuatrimestre":1,"Comisiones":[{"Comisión":"2313-01","Docente/s (1)":"SOSA María Alejnadra / FERREYRA Juan Ignacio","Día/s y horario/s":"LUN 9 A 13","Turno":"Mañana","Aula/s":"7 DARACT II","Modalidad":"SEMIPRESENCIAL","Clase Presencial":"Según cronograma del docente"},{"Comisión":"2313-02","Docente/s (1)":"CANCELA Eugenia / AGUILAR Cecilia","Día/s y horario/s":"LUN 9 A 13","Turno":"Mañana","Aula/s":"7 DARACT II","Modalidad":"SEMIPRESENCIAL","Clase Presencial":"Según cronograma del docente"},{"Comisión":"2313-03","Docente/s (1)":"VILLARREAL Roberto / ANDINO Vanesa","Día/s y horario/s":"LUN 18 A 22","Turno":"Noche","Aula/s":"7 DARACT II","Modalidad":"SEMIPRESENCIAL","Clase Presencial":"Según cronograma del docente"},{"Comisión":"2313-04","Docente/s (1)":"BENEDETTI Gustavo /  ROTH Manuela","Día/s y horario/s":"LUN 18 A 22","Turno":"Noche","Aula/s":"7 DARACT II","Modalidad":"SEMIPRESENCIAL","Clase Presencial":"Según cronograma del docente"}]},
    {"Año":1,"Código":2313,"Asignatura-Actividad":"DIBUJO ARQUITECTÓNICO I","Correlatividad Débil":null,"Correlatividad Fuerte":null,"Horas semanales teórico-prácticas":4,"Cuatrimestre":2,"Comisiones":[{"Comisión":"2313-05","Docente/s (1)":"TARAMASSO María Liliana / ANDINO Vanesa / MONTESANO Alejandro","Día/s y horario/s":"SÁB 9 A 13","Turno":"Mañana","Aula/s":"***","Modalidad":"SEMIPRESENCIAL","Clase Presencial":"Según cronograma del docente"}]},
    {"Año":1,"Código":2314,"Asignatura-Actividad":"FÍSICA","Correlatividad Débil":null,"Correlatividad Fuerte":null,"Horas semanales teórico-prácticas":4,"Cuatrimestre":1,"Comisiones":[{"Comisión":"2314-01","Docente/s (1)":"CABEZON Mariano / PIROLO Gabriel","Día/s y horario/s":"MIÉ 9 A 13","Turno":"Mañana","Aula/s":"7 DARACT II","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2314-02","Docente/s (1)":"INDART Rafael / DISCACCIATI Mariela / VIGO DEANDREIS Leandro","Día/s y horario/s":"MIÉ 9 A 13","Turno":"Mañana","Aula/s":"7 DARACT II","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2314-03","Docente/s (1)":"MEDRANO Rocío / CABEZON Mariano","Día/s y horario/s":"MIÉ 18 A 22","Turno":"Noche","Aula/s":"7 DARACT II","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2314-04","Docente/s (1)":"CORNU Ernesto / CURES Lorena","Día/s y horario/s":"MIÉ 18 A 22","Turno":"Noche","Aula/s":"7 DARACT II","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"}]},
    {"Año":1,"Código":2314,"Asignatura-Actividad":"FÍSICA","Correlatividad Débil":null,"Correlatividad Fuerte":null,"Horas semanales teórico-prácticas":4,"Cuatrimestre":2,"Comisiones":[{"Comisión":"2314-05","Docente/s (1)":"CABEZÓN Mariano / MEDRANO","Día/s y horario/s":"MIÉ 13:30 A 17:30","Turno":"Tarde","Aula/s":"***","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2314-06","Docente/s (1)":"CORNU Ernesto / CURES Lorena","Día/s y horario/s":"MIÉ 13:30 A 17:30","Turno":"Tarde","Aula/s":"***","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"}]},
    {"Año":1,"Código":2315,"Asignatura-Actividad":"INTRODUCCIÓN A LA HISTORIA DE LA ARQUITECTURA Y EL URBANISMO","Correlatividad Débil":null,"Correlatividad Fuerte":null,"Horas semanales teórico-prácticas":5,"Cuatrimestre":1,"Comisiones":[{"Comisión":"2315-01","Docente/s (1)":"GALDO NOVO Natalia / AGUIN Luciano ","Día/s y horario/s":"MIÉ 13 A 18","Turno":"Tarde","Aula/s":"11 DARACT II","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2315-02","Docente/s (1)":"JAUREGUI Fiorella / CORRADINI Claudia","Día/s y horario/s":"MIÉ 13 A 18","Turno":"Tarde","Aula/s":"12 DARACT II","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"}]},
    {"Año":1,"Código":2315,"Asignatura-Actividad":"INTRODUCCIÓN A LA HISTORIA DE LA ARQUITECTURA Y EL URBANISMO","Correlatividad Débil":null,"Correlatividad Fuerte":null,"Horas semanales teórico-prácticas":5,"Cuatrimestre":2,"Comisiones":[{"Comisión":"2315-03","Docente/s (1)":"CORRADINI Claudia /  ABOY Rosa","Día/s y horario/s":"MIÉ 8 A 13","Turno":"Mañana","Aula/s":"***","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2315-04","Docente/s (1)":"YACUZZI Paula / JAUREGUI DÁPOLITO Fiorella Liliana","Día/s y horario/s":"MIÉ 8 A 13","Turno":"Mañana","Aula/s":"***","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2315-05","Docente/s (1)":"DAICH VARELA  Leandro / GALDO NOVO Natalia","Día/s y horario/s":"MIÉ 18 A 23","Turno":"Noche","Aula/s":"***","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2315-06","Docente/s (1)":"ANGERAMI María Clara / SEVILLA Daniel Alejandro","Día/s y horario/s":"MIÉ 18 A 23","Turno":"Noche","Aula/s":"***","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"}]},
    {"Año":1,"Código":2316,"Asignatura-Actividad":"INTRODUCCIÓN A LA TECNOLOGÍA","Correlatividad Débil":2314,"Correlatividad Fuerte":null,"Horas semanales teórico-prácticas":4,"Cuatrimestre":1,"Comisiones":[{"Comisión":"2316-01","Docente/s (1)":"TUCCI Adriana / HERMIDA Adriana / RISSO PATRON Luciana","Día/s y horario/s":"JUE 13:30 A 17:30","Turno":"Tarde","Aula/s":"11 DARACT II","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"}]},
    {"Año":1,"Código":2316,"Asignatura-Actividad":"INTRODUCCIÓN A LA TECNOLOGÍA","Correlatividad Débil":2314,"Correlatividad Fuerte":null,"Horas semanales teórico-prácticas":4,"Cuatrimestre":2,"Comisiones":[{"Comisión":"2316-02","Docente/s (1)":"TUCCI Adriana / ESTARELLAS Rafael","Día/s y horario/s":"JUE 9 A 13","Turno":"Mañana","Aula/s":"***","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2316-03","Docente/s (1)":"HERMIDA Adriana / RISSO PATRON Luciana","Día/s y horario/s":"JUE 9 A 13","Turno":"Mañana","Aula/s":"***","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2316-04","Docente/s (1)":"TUCCI Adriana / RISSO PATRON Luciana","Día/s y horario/s":"JUE 18 A 22","Turno":"Noche","Aula/s":"***","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2316-05","Docente/s (1)":"HERMIDA Adriana / ESTARELLAS Rafael","Día/s y horario/s":"JUE 18 A 22","Turno":"Noche","Aula/s":"***","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"}]},
    {"Año":1,"Código":2317,"Asignatura-Actividad":"MORFOLOGÍA I","Correlatividad Débil":2314,"Correlatividad Fuerte":null,"Horas semanales teórico-prácticas":5,"Cuatrimestre":1,"Comisiones":[{"Comisión":"2317-01","Docente/s (1)":"SANJURJO Moira / SOSA María Alejandra / TINTO Nicolás","Día/s y horario/s":"LUN 13 A 18","Turno":"Tarde","Aula/s":"5 DARACT II","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"}]},
    {"Año":1,"Código":2317,"Asignatura-Actividad":"MORFOLOGÍA I","Correlatividad Débil":2314,"Correlatividad Fuerte":null,"Horas semanales teórico-prácticas":5,"Cuatrimestre":2,"Comisiones":[{"Comisión":"2317-02","Docente/s (1)":"SOSA María Alejandra / STAGNI Laura","Día/s y horario/s":"LUN 8 A 13","Turno":"Mañana","Aula/s":"***","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2317-03","Docente/s (1)":"AGUILAR Cecilia / DE LA FUENTE Lourdes","Día/s y horario/s":"LUN 8 A 13","Turno":"Mañana","Aula/s":"***","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2317-04","Docente/s (1)":"STAGNI Lucía / DANTIN Pamela","Día/s y horario/s":"LUN 18 A 23","Turno":"Noche","Aula/s":"***","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2317-05","Docente/s (1)":"MACHIN Diego","Día/s y horario/s":"LUN 18 A 23","Turno":"Noche","Aula/s":"***","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"}]},
    {"Año":2,"Código":2321,"Asignatura-Actividad":"TALLER DE ARQUITECTURA II","Correlatividad Débil":"2313-2316","Correlatividad Fuerte":2311,"Horas semanales teórico-prácticas":7,"Cuatrimestre":"1-2","Comisiones":[{"Comisión":"2321-01","Docente/s (1)":"BERTOLI Sandra / DÍAZ Mariana Paula","Día/s y horario/s":"MAR 9 A 13 Y VIE 9 A 12","Turno":"Mañana","Aula/s":"18 DARACT I","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2321-02","Docente/s (1)":"PEROTTI Andrea / NORTE María Laura","Día/s y horario/s":"MAR 9 A 13 Y VIE 9 A 12","Turno":"Mañana","Aula/s":"19 DARACT I","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2321-03","Docente/s (1)":"LERNER Lautaro","Día/s y horario/s":"MAR 13:30 A 17:30 Y VIE 14 A 17","Turno":"Tarde","Aula/s":"J003/ 11 DARACT II","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2321-04","Docente/s (1)":"CONTRERAS IRIARTE Julián / AGUIN Luciano","Día/s y horario/s":"MAR 18 A 22 Y VIE 18 A 21","Turno":"Noche","Aula/s":"18 DARACT I","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"},{"Comisión":"2321-05","Docente/s (1)":" BERTOLI Sandra","Día/s y horario/s":"MAR 18 A 22 Y VIE 18 A 21","Turno":"Noche","Aula/s":"19 DARACT I","Modalidad":"PRESENCIAL","Clase Presencial":"TODAS"}]},
    {"Año":2,"Código":2322,"Asignatura-Actividad":"MATEMÁTICAS II","Correlatividad Débil":2312,"Correlatividad Fuerte":2311,"Horas semanales teórico-prácticas":4,"Cuatrimestre":1,"Comisiones":[{"Comisión":"2322-01","Docente/s (1)":"MARCOVECCHIO Claudia / GONZALEZ Ariel Eduardo Germán","Día/s y horario/s":"JUE 9 A 13","Turno":"Mañana","Aula/s":"18 DARACT I","Modalidad":"SEMIPRESENCIAL","Clase Presencial":"Según cronograma del docente"},{"Comisión":"2322-02","Docente/s (1)":"MARSAGLIA Walter / WILSON Florencia","Día/s y horario/s":"JUE 9 A 13","Turno":"Mañana","Aula/s":"19 DARACT I","Modalidad":"SEMIPRESENCIAL","Clase Presencial":"Según cronograma del docente"},{"Comisión":"2322-03","Docente/s (1)":"MARCOVECCHIO Claudia / WILSON Florencia","Día/s y horario/s":"JUE 18 A 22","Turno":"Noche","Aula/s":"18 DARACT I","Modalidad":"SEMIPRESENCIAL","Clase Presencial":"Según cronograma del docente"},{"Comisión":"2322-04","Docente/s (1)":"GONZALEZ Ariel Eduardo Germán / LACABA María Cecilia","Día/s y horario/s":"JUE 18 A 22","Turno":"Noche","Aula/s":"19 DARACT I","Modalidad":"SEMIPRESENCIAL","Clase Presencial":"Según cronograma del docente"}]},
    {"Año":2,"Código":2323,"Asignatura-Actividad":"DIBUJO ARQUITECTÓNICO II","Correlatividad Débil":2313,"Correlatividad Fuerte":2311,"Horas semanales teórico-prácticas":4,"Cuatrimestre":1,"Comisiones":[{"Comisión":"2323-01","Docente/s (1)":"ANDINO Vanesa / VILLARREAL Roberto","Día/s y horario/s":"LUN 9 A 13","Turno":"Mañana","Aula/s":"7 DARACT II","Modalidad":"SEMIPRESENCIAL","Clase Presencial":"Según cronograma del docente"},{"Comisión":"2323-02","Docente/s (1)":"MONTESANO Alejandro / DI FEDE Alicia","Día/s y horario/s":"LUN 9 A 13","Turno":"Mañana","Aula/s":"7 DARACT II","Modalidad":"SEMIPRESENCIAL","Clase Presencial":"Según cronograma del docente"},{"Comisión":"2323-03","Docente/s (1)":"DI FEDE Alicia / FEVRE Mario","Día/s y horario/s":"LUN 18 A 22","Turno":"Noche","Aula/s":"7 DARACT II","Modalidad":"SEMIPRESENCIAL","Clase Presencial":"Según cronograma del docente"},{"Comisión":"2323-04","Docente/s (1)":"MONTESANO Alejandro / TINTO Nicolás","Día/s y horario/s":"LUN 18 A 22","Turno":"Noche","Aula/s":"7 DARACT II","Modalidad":"SEMIPRESENCIAL","Clase Presencial":"Según cronograma del docente"}]},
    {"Año":2,"Código":2324,"Asignatura-Actividad":"HISTORIA DE LA ARQUITECTURA Y EL URBANISMO I","Correlatividad Débil":2315,"Correlatividad Fuerte":2311,"Horas semanales teórico-prácticas":4,"Cuatrimestre":1,"Comisiones":[{"Comisión":"2324-01","Docente/s (1)":"YACUZZI Paula / CORRADINI Claudia","Día/s y horario/s":"MIÉ 9 A 13","Turno":"Mañana","Aula/s":"18 DARACT I","Modalidad":"SEMIPRESENCIAL","Clase Presencial":"Según cronograma del docente"},{"Comisión":"2324-02","Docente/s (1)":"ATANASOPULOS Andrea / JAUREGUI Fiorella","Día/s y horario/s":"MIÉ 9 A 13","Turno":"Mañana","Aula/s":"19 DARACT I","Modalidad":"SEMIPRESENCIAL","Clase Presencial":"Según cronograma del docente"},{"Comisión":"2324-03","Docente/s (1)":"AGUIN Luciano / SEVILLA Daniel","Día/s y horario/s":"MIÉ 18 A 22","Turno":"Noche","Aula/s":"18 DARACT I","Modalidad":"SEMIPRESENCIAL","Clase Presencial":"Según cronograma del docente"},{"Comisión":"2324-04","Docente/s (1)":"YACUZZI Paula","Día/s y horario/s":"MIÉ 18 A 22","Turno":"Noche","Aula/s":"19 DARACT I`,` ... TRUNCATED ...

INSERT INTO items (categoria, titulo, descripcion, tags, enlaces, datos_especificos)
SELECT
  'asignatura',
  (a->> 'Asignatura-Actividad') as titulo,
  concat('Asignatura de ', (p->> 'carrera'), ' — Año ', COALESCE(a->> 'Año','')) as descripcion,
  ARRAY[]::text[],
  '[]'::jsonb,
  -- Guardamos metadatos de la asignatura y un resumen compacto de las comisiones
  jsonb_build_object(
    'carrera', p->> 'carrera',
    'codigo_carrera', p->> 'codigo',
    'organizacion_curricular', p->> 'organizacion_curricular',
    'plan_de_estudios', p->> 'plan_de_estudios',
    'ano', a->> 'Año',
    'codigo_asignatura', a->> 'Código',
    'horas', a->> 'Horas semanales teórico-prácticas',
    'cuatrimestre', a->> 'Cuatrimestre',
    'correlatividad_debil', a->> 'Correlatividad Débil',
    'correlatividad_fuerte', a->> 'Correlatividad Fuerte',
    -- Resumen: número de comisiones y una muestra reducida (primera comisión con docente+horario)
    'comisiones_count', (CASE WHEN a->'Comisiones' IS NULL THEN 0 ELSE jsonb_array_length(a->'Comisiones') END),
    'comision_sample', (
      CASE WHEN a->'Comisiones' IS NULL THEN NULL
      ELSE (
        SELECT jsonb_build_object(
          'Comision', c->> 'Comisión',
          'Docente', c->> 'Docente/s (1)',
          'Horario', c->> 'Día/s y horario/s'
        )
        FROM jsonb_array_elements(a->'Comisiones') as c
        LIMIT 1
      ) END
    )
  ) as datos_especificos
FROM payload p, jsonb_array_elements(p.p->'asignaturas') as a
ON CONFLICT DO NOTHING;

COMMIT;

-- Nota: este script es reutilizable: reemplaza el JSON en la sección `payload` por otro
-- que tenga la misma estructura para insertar asignaturas de otras carreras.
